### ISSUE TITLE
refresching is misspelt

### ISSUE THREAD

**Issue by EphraimB** [Studio384/ChangeWindows#12]
It should say refreshing

**Comment by EphraimB** [comment]
Improved logic for refresching the Live tiles on the start screen

should say

Improved logic for refreshing the Live tiles on the start screen

How is this invalid?

**Comment by Studio384** [comment]
Because your report is useless. You're ignoring all the guidelines this repository has.














And I don't like liars.

**Comment by EphraimB** [comment]
How am I lying?

**Comment by Studio384** [comment]
Buildfeed. Yeah, I know who you are.

**Comment by EphraimB** [comment]
Why are you being very rude to me? I deserve some credit for pointing that spelling mistake out to you.

**Comment by Studio384** [comment]
No need for credit where no credit is duet. This was already reporter correctly by someone else.
