### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jlgager24** [Studio384/ChangeWindows#16]
First of all thanks for all your hard work with the site! Without your site the Windows 10 Repository on MyDigitalLife would not be as accurate. I am jlgager the creator of that thread. When I update the thread your site is where I go first to check for a new build. I am making a desktop app for your site that gives action center/tray notifications when a new build releases. (I code in C#) An API or RSS feed would be helpful for that to work smoothly and I am willing to help you guys build one of those too. Also I can help with web hosting and design. (I self host Wordpress and PHPBB) Feel free to PM me on MDL or the email I provided in your most recent survey.

**Comment by Studio384** [comment]
We currently don't have an API or RSS feed, but an API is something I'm looking into. Anyway, ChangeWindows.org runs on a system build from the ground up by myself for this exact purpose (although it was made in a rush). Any suggestions for an API to run on a MySQL database/PHP system?

**Comment by jlgager24** [comment]
I see that you got something up and running before I even got off work lol. Looks good so far!

I don't know php that well but here is a link to some tutorials that might help you:
http://blog.mashape.com/list-of-40-tutorials-on-how-to-create-an-api/

I really suggest using api developer keys to save you on server costs and server load.

I could make an API in Ruby on Rails or C#/ASP if you would rather do that depending on what hosting server you use, Apache or IOS respectively.

I should be releasing the first version of the app in the next few days.

Do you have an .ico icon I can use for the app or should I just use a white version of the windows 10 logo? I can make you one if you want as I know some photoshop basics.

Also if you need help, I am willing to step in and help during your trips in July to keep the site updated.

Thanks again!

**Comment by Studio384** [comment]
You want to use the ChangeWindows logo for your app?

**Comment by jlgager24** [comment]
In order for someone to be able to use the web api they would have to sign up for a free account. When they signup they receive a randomly generated api developer key that they then use with every request they make to the api. This allows you to limit the amount of requests in a time period to limit load on the server. Basically it stops someone from running 100+ requests an hour for example.

and yes I would like to please use the ChangeWindows logo for the app but I would need a logo that could be the icon that would be more square and without text, like the GitHub logo for example.

and can we continue this by email lol? I can email you at contact@studio384.be?
