### ISSUE TITLE
APIs have gone missing

### ISSUE THREAD

**Issue by twpol** [Studio384/ChangeWindows#20]
The APIs, documented on https://github.com/Studio384/ChangeWindows/blob/master/api.md, seem to have gone missing - they're all 404s now. Could we have them back, please? :)

**Comment by Studio384** [comment]
I'm terribly sorry, they should be available again.

However, I would like to point out that we're going to move to an updated structure in the near future that will deprecate most if not all of these APIs, documentation on what is going to change will follow soon.

**Comment by Studio384** [comment]
For more info on the changes to our APIs, please read the updated documentation in our astrid-branch: https://github.com/Studio384/ChangeWindows/blob/astrid/api.md

**Comment by twpol** [comment]
Thanks, don't mind the APIs changing as long as docs do too. :)

**Comment by Studio384** [comment]
I've updated the documentation on the API for version 2.5 and 3.0.

**[ChangeWindows 2.5 API information](https://github.com/Studio384/ChangeWindows/blob/master/api.md)**, also notes what changes with v3
**[ChangeWindows 3.0 API information](https://github.com/Studio384/ChangeWindows/blob/astrid/api.md)**
