### ISSUE TITLE
Consider putting changelogs into our own database

### ISSUE THREAD

**Issue by Studio384** [Studio384/ChangeWindows#33]
With the future version of ChangeWindows, I want to move back to the system like it was with ChangeWindows 1.0: where the changelogs are stored in our own database rather than on GitHub.

**Comment by twpol** [comment]
Would this mean no longer having them in GitHub, where people can potentially contribute? I am not sure if anyone really did contribute via the files in GitHub though, so it'd be quite understandable if people weren't using the opportunity.

**Comment by Studio384** [comment]
Actually no, this isn't going to happen anymore. ChangeWindows used to pull its changelogs from GitHub, but since ChangeWindows 3.0 the website keeps its own local version which drastically improves performance. The GitHub repository will continue to be maintained, but we'll make commits less often.
