### ISSUE TITLE
IoT builds' release date problem

### ISSUE THREAD

**Issue by win98se** [Studio384/ChangeWindows#54]
For IoT builds, why 14931.1001's release date (5 October 2016) is later then 14936.1000 (29 September 2016)?

As seen in the IoT tab [here](https://changewindows.org/milestone/redstone2#iot).

If there are errors, please fix. Thank you.

**Comment by Studio384** [comment]
Thanks for pointing out, it has been fixed.

**Comment by win98se** [comment]
Thank you.
