### ISSUE TITLE
All mobile builds with build numbers 152xx should be in feature2

### ISSUE THREAD

**Issue by win98se** [Studio384/ChangeWindows#55]
You've listed 15235 as a build of _feature2_.

According to https://buildfeed.net/lab/feature2/, all mobile builds which belonged to _redstone3_ (15204, 15205, 15207, 15208, 15210, 15213, 15215, 15222, 15223, 15226, 15228, 15230) should be moved to _feature2_, because all these builds are in the feature2 lab, instead of Redstone 3 labs (such as rs_prerelease).

**Comment by Studio384** [comment]
We're aware. During an upgrade to ChangeWindows yesterday, these builds all got rolled back to Redstone 3. Having said that, Buildfeed isn't an official source and feature2 is in fact a Redstone 3-lab itself.
